name: Create EXE

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner with Node.js 16

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0  # Specify the Python version you need
          architecture: x64  # Use x64 or x86 based on your requirements

      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
        working-directory: ./  # Modify this path

      - name: Create .env File
        run: echo 'CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}' > .env

      - name: Create Date File
        run: python -c "import datetime; print(datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ'))" > date.txt
        
      - name: Change Version File
        run: python control_version.py

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --console --icon "bot.ico" --name "AutoEmail" --clean --add-data "attachment.pdf:." --add-data "date.txt:." --add-data ".env:." --add-data "template.docx:." --distpath ./output "auto_email.py"
        working-directory: ./  # Modify this path

      - name: Copy EXE to GitHub workspace
        run: |
          git config --global user.email "chandanhans2003@gmail.com"
          git config --global user.name "ChandanHans"
          git add -f ./output/AutoEmail.exe
          git add -f ./version.txt
          git commit -m "Update AutoEmail.exe"
          git push
